import React,{useState} from 'react'
import Sidebar from '../Sidebar/Sidebar'
import NavbarMenu from '../NavbarMenu/NavbarMenu'
import { Button, Col, Container , Row ,Form ,Tooltip,OverlayTrigger} from 'react-bootstrap'
import CreatableSelect from 'react-select/creatable';
import { ActionMeta, OnChangeValue } from 'react-select';
import { ToastContainer, toast } from 'react-toastify';

import { Link } from 'react-router-dom';
const FilterStudent = () => {
    const [showskill, setshowskill]=useState(false);
    const handleShowskill = ()=> setshowskill(!showskill)
    const [showdropdown, setshowdropdown] =useState(false);
 const handleShowdropdown = () => 
   setshowdropdown(!showdropdown)
   const [show4, setShow4] = useState(false);
   const handleClose4 = () => setShow4(false);
   const handleShow4 = () => setShow4(true);
   const [show3, setShow3] = useState(false);
   const handleClose3 = () => setShow3(false);
   const handleShow3 = () => setShow3(true);
   const options = [
    {label:"Virtual/Telephonic- Any mutually decided time. (this week/next week)", value:"Virtual/Telephonic- Any mutually decided time. (this week/next week)"},
    {label:"F2F- Any mutually decided time (this week/next week)", value:"F2F- Any mutually decided time (this week/next week)"},
    {label:"Create", value:""}
  ]
    // const options=[
    //     {label:"Negotiable", value:"Negotiable"},
    //     {label:"Non-Negotiable", value:"Non-Negotiable"},
    // ]
    // const option1=[
    //     {label:"Yes", value:"Yes"},
    //     {label:"No", value:"No"},
    // ]
    const   handleChange = (
        newValue: OnChangeValue<ColourOption, false>,
        actionMeta: ActionMeta<ColourOption>
      ) => {
        console.group('Value Changed');
        console.log(newValue);
        console.log(`action: ${actionMeta.action}`);
        console.groupEnd();
      };
    const   handleInputChange = (inputValue: any, actionMeta: any) => {
        console.group('Input Changed');
        console.log(inputValue);
        console.log(`action: ${actionMeta.action}`);
        console.groupEnd();
      };
  return (
    <div>
        <Sidebar />
        <NavbarMenu />
        <div className='people'>
          <h4 className='mt-5 text-muted text-center mt-5'>Filter Candidates List</h4>
   
        <Container className='search-contact'>
            
            <Form>
        <Row>
            <Col xs={12}>
              <Form.Group className='mt-2 mb-2'>
                <Form.Label className='fw-bold'>Candidate ID </Form.Label>
                <Form.Control type='text' name="alphnumericid" placeholder='(8 digit alpha numeric ID generated by system)' />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>JD number </Form.Label>
                <Form.Control type="text" defaultValue="1" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>Client name </Form.Label>
                <Form.Control type="text" defaultValue="Pkrs" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>JD title  </Form.Label>
                <Form.Control type="text" defaultValue="testing" />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={4}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>JD location </Form.Label>
                <Form.Control type="text" defaultValue="India" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>Recruiter ID  </Form.Label>
                <Form.Control type="text" defaultValue="001" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>Candidate name  </Form.Label>
                <Form.Control type="text" defaultValue="Prashant Kumar" />
              </Form.Group>
            </Col>
          </Row>
          <Row>
          <Col xs={12}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>Current designation  </Form.Label>
                <Form.Control type="text" />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={12}>
              <Form.Label className='fw-bold mb-3 mt-3'>Current salary <OverlayTrigger placement='bottom' overlay={<Tooltip id="tooltip-disabled">Current Salary in lacs/annum</Tooltip>}><span><i className='fas fa-info-circle ms-2'/></span></OverlayTrigger></Form.Label>
               <Row>
                 <Col xs={4}>
                  <h6>Fix</h6>
                  <Form.Control />
                  <span style={{fontSize:"0.75rem", color:"blue"}}>lacs per annum</span>
                 </Col>
                 <Col xs={4}>
                  <h6>variable</h6>
                  <Form.Control />
                  <span style={{fontSize:"0.75rem", color:"blue"}}>lacs per annum</span>
                 </Col>
                 <Col xs={4}>
                  <h6>Total salary </h6>
                  <Form.Control />
                  <span style={{fontSize:"0.75rem", color:"blue"}}>lacs per annum</span>
                 </Col>
               </Row>
            </Col>
          </Row>
          <Row>
            <Col xs={7}>
            <Form.Label className='mt-3 fw-bold'>Last Appraisal of the candidate </Form.Label>
              <div className='d-flex'>
                
                <Form.Select>
                  <option value="January">January</option>
                  <option value="feb">Feb</option>
                  <option value="March">March</option>
                  <option value="April">April</option>
                  <option value="May">May</option>
                  <option value="June">June</option>
                  <option value="July">July</option>
                  <option value="August">August</option>
                  <option value="September">September</option>
                  <option value="October">October</option>
                  <option value="November">November</option>
                  <option value="December">December</option>
                </Form.Select>
                <Form.Select>
                  <option value="2020">2020</option>
                  <option value="2021">2021</option>
                  <option value="2021">2022</option>
                  <option value="2022">2020</option>
                  <option value="2023">2023</option>
                  <option value="2024">2024</option>
                  <option value="2025">2025</option>
                  <option value="2026">2026</option>
                  <option value="2027">2027</option>
                  <option value="2028">2028</option>
                  <option value="2029">2029</option>
                  <option value="2030">2030</option>
                </Form.Select>
              </div>
            </Col>
          </Row>
          <Row>
            <Col xs={12}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3' >Expected salary (Percentage growth or number - lacs per annum ) </Form.Label> <OverlayTrigger placement='bottom' overlay={<Tooltip id="tooltip-disabled">lacs per annum</Tooltip>}><span><i className='fas fa-info-circle ms-2'/></span></OverlayTrigger>
                <div className='d-flex'>
                  <Form.Control type='text' />
                  <Form.Select>
                    <option value="Negotiable">Negotiable</option>
                    <option value="Non-Negotiable">Non-Negotiable</option>
                  </Form.Select>
                </div>
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Total Experience </Form.Label>
                <Form.Control type="text"  />
              </Form.Group>
            </Col>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Education </Form.Label>
                <Form.Control type="text"  />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Current organization  </Form.Label>
                <Form.Control type="text"  />
              </Form.Group>
            </Col>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Current location </Form.Label>
                <Form.Control as="textarea" rows={3} type="address"  />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Candidate mobile number </Form.Label>
                <Form.Control type="tel" placeholder='Phone Number' />
              </Form.Group>
            </Col>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Notice period ?  </Form.Label>
                <Form.Select>
                  <option value='Immediate'>Immediate</option>
                  <option value='15 days'>15 days</option>
                  <option value='21 days '>21 days </option>
                  <option value='30 days'>30 days</option>
                  <option value='45 days'>45 days</option>
                  <option value='2 months'>2 months</option>
                  <option value='75 days'>75 days</option>
                  <option value='90 days'>90 days</option>

                </Form.Select>
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
            <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Negotiable to  </Form.Label>
                <Form.Select>
                  <option value='Immediate'>Immediate</option>
                  <option value='15 days'>15 days</option>
                  <option value='21 days '>21 days </option>
                  <option value='30 days'>30 days</option>
                  <option value='30 days'>45 days</option>
                  <option value='2 months'>2 months</option>
                  <option value='75 days'>75 days</option>
                  <option value="Non Negotiable">Non Negotiable</option>

                </Form.Select>
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
           <Form.Label className='mt-3 fw-bold'>JD sent to candidate ?</Form.Label>
           <div className='d-flex'>
            <Form.Check type="radio" label="Yes" Name="jdsent" value='Yes' />
            <Form.Check className='mx-3' type="radio" label="No" Name="jdsent" value='No' />
           </div>
            </Col>
            <Col xs={6}>
        
                <Form.Label className='fw-bold mt-3'>Candidate availability for the interview ?</Form.Label>
                {/* <Form.Select>
                  <option >Select</option>
                  <option value='Virtual/Telephonic- Any mutually decided time. (this week/next week)'> </option>
                  <option value='F2F- Any mutually decided time (this week/next week)'></option>
                  <option value='Others'>Others</option>
                </Form.Select> */}
                  
                        
                        <CreatableSelect
                                isMulti
                                isClearable
                                onChange={handleChange}
                                onInputChange={handleInputChange}
                                options={options}
                            />
                            
                        
              <Form.Label className='fw-bold mt-3 mb-3'> </Form.Label>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className="fw-bold">Recruiter’s remarks <i className="fas fa-info-circle ms-3" style={{color:'black'}} onClick={handleShow3}></i></Form.Label>
                
              </Form.Group>
            </Col>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Date and Time of adding a candidate</Form.Label>
                <div className='d-flex'>
                  <Form.Control type="date" />
                  <Form.Control type="time" />
                </div>
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={12} >
              
              <div className=' mt-3  '>
                
                <Form.Check type="checkbox" label='Candidate is currently Not working/Jobless ' className='mx-2' onClick={()=>{toast.error("Not working, immediate joiner")}}/><span  style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />If ytou click this option,this means that the candidate is not currently working & an immediate joiner</span>
                <Form.Check type="checkbox" label='Is candidate having an offer/serving the notice period?' className='mx-2' onClick={()=>{toast.error("Found strong need factor for change")}}/><span  style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />If ytou click this option,this means that the candidate is not currently working & an immediate joiner</span>
                <Form.Check type="checkbox" label='Relocation case? ' className='mx-2' onClick={()=>{toast.warning("Relocation case")}} /><span  style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />Did you observe for some reason, candidate want to relocate to the place of JD? if yes, please tick this checkbox . it will indicate that ,it's a relocation case</span>
              
                <div className='d-flex'>
                <Form.Check type="checkbox" label='Career stability? ' className='mx-2' onClick={handleShowdropdown} /><span  style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />This is not a mandatory field. It is optional</span>

                </div>
                <div className={showdropdown? 'showdropdown1': 'showdropdown'}>
                  <Form.Check type='checkbox' label="Has the candidate spent more than 3 years is the current organization?" className='mx-5 mt-3 mb-3 fw-bold'/>
                  <Form.Check type='checkbox' label="Candidate has worked with how many companies in last how many years?" className='mx-5 mt-3 fw-bold'/>
                  <span className='mx-5' style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />This is not a mandatory field. It is optional</span>
                  <span className='mx-5 mb-5' style={{fontSize:'0.75rem', color:'green'}} onClick={handleShow4}><i className="fas fa-question me-3"></i>Guideline- what is called career stability?</span>
                    <Row>
                      <Col sm={4} className="mx-5">
                      <Form.Label className='mt-2'>Work With:</Form.Label>
                  <Form.Select>
                    <option value='1'>1</option>
                    <option value='2'>2</option>
                    <option value='3'>3</option>
                    <option value='4'>4</option>
                    <option value='5'>5</option>
                    <option value='6'>6</option>
                    <option value='7'>7</option>
                  </Form.Select>
                      </Col>
                      <Col sm={4} className="mx-5">
                      <Form.Label className='mt-2'>Companies in last :</Form.Label>
                  <Form.Select>
                    <option value='1 year'>1 Year</option>
                    <option value='2 Years'>2 Years</option>
                    <option value='3 Years'>3 Years</option>
                    <option value='4 Years'>4 Years</option>
                    <option value='5 Years'>5 Years</option>
                    <option value='6 Years'>6 Years</option>
                    <option value='7 Years'>7 Years</option>
                    <option value='8 Years'>8 Years</option>
                    <option value='9 Years'>9 Years</option>
                    <option value='10 Years'>10 Years</option>
                    <option value='11 Years'>11 Years</option>
                    <option value='12 Years'>12 Years</option>
                    <option value='13 Years'>13 Years</option>
                    <option value='14 Years'>14 Years</option>
                    <option value='15 Years'>15 Years</option>
                    <option value='16 Years'>16 Years</option>
                    <option value='17 Years'>17 Years</option>
                    <option value='18 Years'>18 Years</option>
                    <option value='19 Years'>19 Years</option>
                    <option value='20 Years'>20 Years</option>
                    <option value='21 Years'>21 Years</option>
                    <option value='22 Years'>22 Years</option>
                    <option value='23 Years'>23 Years</option>
                    <option value='24 Years'>24 Years</option>
                    <option value='25 Years'>25 Years</option>
                    <option value='26 Years'>26 Years</option>
                    <option value='27 Years'>27 Years</option>
                    <option value='28 Years'>28 Years</option>
                    <option value='29 Years'>29 Years</option>
                    <option value='30 Years'>30 Years</option>
                    <option value='31 Years'>31 Years</option>
                    <option value='32 Years'>32 Years</option>
                    <option value='33 Years'>33 Years</option>
                    <option value='34 Years'>34 Years</option>
                    <option value='35 Years'>35 Years</option>
                    <option value='36 Years'>36 Years</option>
                    <option value='37 Years'>37 Years</option>
                    <option value='38 Years'>38 Years</option>
                    <option value='39 Years'>39 Years</option>
                    <option value='40 Years'>40 Years</option>
                  </Form.Select>
                      </Col>
                    </Row>
                </div>
                
                
                
                <Form.Check type="checkbox" label='Is the candidate flexible to attend rounds of interview? ' className='mx-2' />
                <Form.Check type="checkbox" label='Communication skills? ' className='mx-2' onClick={handleShowskill} /><span  style={{fontSize:'0.75rem', color:'black'}}><i className='fas fa-info-circle me-3' />If you observe very strong or average communication . only then click this field. In nornmal cases, no need to tick this field.</span>
                <div className={showskill? 'showskill1':'showskill'}>
                  <Form.Select>
                    <option value='Excellent'>Excellent</option>
                    <option value='Good'>Good</option>
                    <option value='Average'>Average</option>
                  </Form.Select>
                </div>
              </div>
            </Col>
          </Row>
          <Row>
            <Col xs={12}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Any special comments by user</Form.Label>
              <Form.Control as="textarea" row={3} />
              </Form.Group>
            </Col>
          </Row>

          <Button variant='success' className='mt-3'>Add candidate</Button>
        </Form>
        </Container>
        </div>
        <div className='d-flex justify-content-center title-absolute py-4 border-top'>
                        <Button variant='secondary' className='mx-3 text-white'>Reset</Button>
                        <Link to='/ListOfCandidate'><Button variant='primary' className='mx-3 text-white'>Search</Button></Link>
                        <Link to='/ListOfCandidate'><Button variant='danger' className='mx-3 text-white'>Colse</Button></Link>
                    </div>
    </div>
  )
}

export default FilterStudent